# 作业第16讲

In [1]:
import numpy as np

# 矩阵C

In [2]:
C = np.array([
    [1, 0, 0, 0, 0, 1],
    [0, 1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 1, 0],
    [0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 1]
])

# 奇异值分解

In [3]:
U, Sigma, VT = np.linalg.svd(C)

# U2

In [4]:
# 保留前两列
U2 = U[:,:2]
print(U2.round(6))

[[ 0.        0.707107]
 [ 0.        0.      ]
 [-0.        0.      ]
 [ 0.        0.      ]
 [-0.        0.      ]
 [-0.723607  0.      ]
 [-0.276393  0.      ]
 [-0.447214  0.      ]
 [-0.447214  0.      ]
 [ 0.        0.5     ]
 [ 0.        0.5     ]]


# Sigma2

In [5]:
# 保留前两个特征值, 并张成对角矩阵
Sigma2 = np.diag(Sigma[:2])
print(Sigma2.round(6))

[[1.902113 0.      ]
 [0.       1.847759]]


# VT2

In [6]:
# 保留前两行
VT2 = VT[:2,:]
print(VT2.round(6))

[[-0.        0.        0.       -0.525731 -0.850651  0.      ]
 [ 0.382683  0.        0.        0.        0.        0.92388 ]]


# 2-秩逼近矩阵C2

In [7]:
C2 = np.around(np.matmul(np.matmul(U2, Sigma2), VT2), 6)
print(C2.round(6))

[[ 0.5       0.        0.        0.        0.        1.207107]
 [ 0.        0.        0.       -0.       -0.        0.      ]
 [ 0.        0.        0.        0.        0.        0.      ]
 [ 0.        0.        0.       -0.       -0.        0.      ]
 [ 0.        0.        0.        0.        0.        0.      ]
 [ 0.        0.        0.        0.723607  1.17082   0.      ]
 [ 0.        0.        0.        0.276393  0.447214  0.      ]
 [ 0.        0.        0.        0.447214  0.723607  0.      ]
 [ 0.        0.        0.        0.447214  0.723607  0.      ]
 [ 0.353553  0.        0.        0.        0.        0.853553]
 [ 0.353553  0.        0.        0.        0.        0.853553]]
